baseURL = "https://breadtube.tv/"
languageCode = "en-us"
title = "BreadTube.tv"

# https://fontawesome.com/v4.7.0/cheatsheet/

[ params ]
OpenLinksInNewWindow = true

[[ params.nav ]]
name = "Reddit"
href = "https://reddit.com/r/breadtube"
icon = "reddit"

[[ params.nav ]]
name = "Discord"
tag = "https://discord.gg/5MGeFv9"
icon = "discord"

[[ params.nav ]]
name = "Twitter"
tag = "https://twitter.com/breadtubetv"
icon = "twitter"

[[ params.nav ]]
name = "Github"
href = "https://github.com/breadtubetv/breadtubetv"
icon = "github"
